// <auto-generated />
namespace Polly.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Index2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Index2));
        
        string IMigrationMetadata.Id
        {
            get { return "201811081750312_Index2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
